import type { Config } from 'tailwindcss';

const config: Config = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        background: 'var(--background)',
        foreground: 'var(--foreground)',
        paper: '#FBF5E6',
        paperDeep: '#F4EAD0',
        paperShadow: '#E8DDC0',
        ink: '#3D3326',
        inkSoft: '#6B5D4A',
        inkPale: '#A89A82',
        rose: '#F2C7C1',
        roseDeep: '#D89991',
        butter: '#F4DFA5',
        butterDeep: '#D9B863',
        mint: '#C9DFC8',
        mintDeep: '#7FA77E',
        sky: '#C8D8E4',
        skyDeep: '#6E92A8',
        lilac: '#D8CCE0',
        lilacDeep: '#A187B5',
        peach: '#F4D2B5',
        peachDeep: '#D49A6A',
        catFur: '#FAF6EE',
        catShadow: '#E2D9C8',
        catGray: '#9E9586',
        catGrayDeep: '#6E665A',
        catPink: '#E4ADA8',
        ember: '#E47B5A',
        'bunny-bg-cream': '#FBF5E6',
        'bunny-bg-warmpaper': '#F4EAD0',
        'bunny-bg-sky': '#C8D8E4',
        'bunny-bg-night': '#3D3326',
        'bunny-grass': '#C9DFC8',
        'bunny-grass-deep': '#7FA77E',
        'bunny-wood': '#D49A6A',
        'bunny-wood-deep': '#6B5D4A',
        'bunny-leaf': '#7FA77E',
        'bunny-pink': '#F2C7C1',
        'bunny-pink-soft': '#F4D2B5',
        'bunny-gold': '#F4DFA5',
        'bunny-berry': '#E47B5A',
        'bunny-ink': '#3D3326',
        'bunny-ink-soft': '#6B5D4A',
        'bunny-ink-faint': '#A89A82',
      },
      borderRadius: {
        'paper-sm': '10px',
        'paper-md': '18px',
        'paper-lg': '28px',
        'paper-pill': '9999px',
        'bunny-sm': '10px',
        'bunny-md': '18px',
        'bunny-lg': '28px',
        'bunny-pill': '9999px',
      },
      boxShadow: {
        paper: '3px 4px 0 #E8DDC0',
        'paper-hero': '6px 7px 0 #E8DDC0',
        'state-mint': '0 0 0 6px rgba(201, 223, 200, 0.53)',
        'state-peach': '0 0 0 6px rgba(244, 210, 181, 0.53)',
        'state-sky': '0 0 0 4px rgba(200, 216, 228, 0.67)',
        soft: '3px 4px 0 #E8DDC0',
        medium: '5px 6px 0 #E8DDC0',
        bunny: '3px 4px 0 #E8DDC0',
      },
      fontFamily: {
        zh: ['var(--font-zh)'],
        display: ['var(--font-display)'],
        en: ['var(--font-en)'],
        'en-script': ['var(--font-en-script)'],
        mono: ['var(--font-mono)'],
      },
    },
  },
  plugins: [],
};
export default config;
